/**
 * 40-city seed dataset for the RelocateWise MVP.
 *
 * This is the **canonical** source of truth for the city data the API
 * serves. The Postgres migration in /db/migrations/ copies the same
 * shape; updates to either side must be reflected on the other.
 * A JSON mirror of the array lives in /db/seeds/cities.json for the
 * boot-time seed path (Architecture §5.3).
 *
 * Source: curated manually by the founder from public data (Numbeo,
 * Wikipedia, EU/UN/World Bank). Each city's `last_updated` is the date
 * the founder signed off on the record. The dataset is small enough
 * to be reviewed top-to-bottom in a few minutes.
 *
 * Region distribution (Architecture §5.2, CEO decision 2026-06-02):
 *   North America  : 15
 *   Europe         : 10
 *   Asia-Pacific   :  5
 *   Latin America  :  5
 *   Other          :  5
 *   --------------------------------
 *   Total          : 40
 *
 * Dimension scoring scale is 1..5 (1 = poor, 5 = excellent) for the
 * scalar dimensions; career and community are 0..3 sub-scores per
 * industry / tag reflecting the *strength* of that industry / vibe.
 */
import type { City } from '@relocatewise/shared';

const c = (
  slug: string,
  name: string,
  country: string,
  country_code: string,
  region: string,
  lat: number,
  lng: number,
  climate: City['dimensions']['climate']['label'],
  cost: number,
  housing: number,
  education: number,
  healthcare: number,
  career: City['dimensions']['career'],
  community: City['dimensions']['community'],
  description: string,
  last_updated = '2026-01-15',
): City => ({
  slug,
  name,
  country,
  country_code,
  region,
  lat,
  lng,
  description,
  last_updated,
  dimensions: {
    climate: { label: climate },
    cost,
    housing,
    career,
    education,
    healthcare,
    community,
  },
});

export const SEED_CITIES: readonly City[] = [
  // -----------------------------------------------------------------------
  // North America (15)
  // -----------------------------------------------------------------------
  c(
    'new-york-us',
    'New York City',
    'United States',
    'US',
    'North America',
    40.7128,
    -74.006,
    'Continental',
    1,
    1,
    5,
    4,
    { tech: 3, finance: 3, healthcare: 3, creative: 3, manufacturing: 1 },
    { urban: 3, suburban: 0, rural: 0, coastal: 2, mountain: 0, arts_culture: 3, family_oriented: 1, expat_friendly: 3 },
    'The financial and cultural capital of the U.S., dense and walkable, with the largest metropolitan economy in the world.',
  ),
  c(
    'austin-us',
    'Austin',
    'United States',
    'US',
    'North America',
    30.2672,
    -97.7431,
    'Tropical',
    2,
    2,
    5,
    4,
    { tech: 3, finance: 1, healthcare: 1, creative: 2, manufacturing: 1 },
    { urban: 2, suburban: 2, rural: 0, coastal: 0, mountain: 0, arts_culture: 2, family_oriented: 1, expat_friendly: 1 },
    "Austin's tech boom has made it one of the fastest-growing U.S. metros, with a young population, live-music scene, and (until recently) no state income tax.",
  ),
  c(
    'toronto-ca',
    'Toronto',
    'Canada',
    'CA',
    'North America',
    43.6532,
    -79.3832,
    'Continental',
    2,
    2,
    5,
    5,
    { tech: 3, finance: 3, healthcare: 2, creative: 2, manufacturing: 2 },
    { urban: 3, suburban: 1, rural: 0, coastal: 0, mountain: 0, arts_culture: 3, family_oriented: 1, expat_friendly: 3 },
    'Canada\'s largest city and financial centre, with a globally recognized diversity: over half of residents were born outside Canada.',
  ),
  c(
    'vancouver-ca',
    'Vancouver',
    'Canada',
    'CA',
    'North America',
    49.2827,
    -123.1207,
    'Temperate',
    2,
    1,
    5,
    5,
    { tech: 2, finance: 1, healthcare: 1, creative: 2, manufacturing: 1 },
    { urban: 2, suburban: 1, rural: 0, coastal: 3, mountain: 2, arts_culture: 2, family_oriented: 1, expat_friendly: 3 },
    'Pacific coast city framed by mountains and ocean, with strong Asian-Canadian cultural ties and a mild (rainy) climate.',
  ),
  c(
    'san-francisco-us',
    'San Francisco',
    'United States',
    'US',
    'North America',
    37.7749,
    -122.4194,
    'Temperate',
    1,
    1,
    5,
    5,
    { tech: 3, finance: 2, healthcare: 2, creative: 2, manufacturing: 1 },
    { urban: 3, suburban: 0, rural: 0, coastal: 3, mountain: 1, arts_culture: 3, family_oriented: 0, expat_friendly: 2 },
    'Pacific coast tech capital: high salaries offset by the highest cost of living in the U.S., with a famously entrepreneurial culture.',
  ),
  c(
    'seattle-us',
    'Seattle',
    'United States',
    'US',
    'North America',
    47.6062,
    -122.3321,
    'Temperate',
    1,
    1,
    5,
    5,
    { tech: 3, finance: 1, healthcare: 2, creative: 1, manufacturing: 2 },
    { urban: 2, suburban: 1, rural: 0, coastal: 2, mountain: 3, arts_culture: 2, family_oriented: 1, expat_friendly: 1 },
    'Pacific Northwest tech hub anchored by Amazon and Microsoft; surrounded by mountains and water, with a famously rainy climate.',
  ),
  c(
    'boston-us',
    'Boston',
    'United States',
    'US',
    'North America',
    42.3601,
    -71.0589,
    'Continental',
    1,
    1,
    5,
    5,
    { tech: 3, finance: 2, healthcare: 3, creative: 1, manufacturing: 1 },
    { urban: 2, suburban: 1, rural: 0, coastal: 2, mountain: 0, arts_culture: 3, family_oriented: 1, expat_friendly: 2 },
    "America's college town: dense, walkable, and an anchor of biotech, higher education, and medical research.",
  ),
  c(
    'chicago-us',
    'Chicago',
    'United States',
    'US',
    'North America',
    41.8781,
    -87.6298,
    'Continental',
    2,
    2,
    4,
    5,
    { tech: 2, finance: 3, healthcare: 2, creative: 2, manufacturing: 2 },
    { urban: 3, suburban: 1, rural: 0, coastal: 1, mountain: 0, arts_culture: 3, family_oriented: 1, expat_friendly: 2 },
    'Midwestern hub famous for its architecture, deep-dish pizza, and the Chicago Mercantile Exchange. Large and affordable by coastal standards.',
  ),
  c(
    'denver-us',
    'Denver',
    'United States',
    'US',
    'North America',
    39.7392,
    -104.9903,
    'Continental',
    2,
    2,
    4,
    4,
    { tech: 2, finance: 1, healthcare: 1, creative: 1, manufacturing: 1 },
    { urban: 2, suburban: 2, rural: 0, coastal: 0, mountain: 3, arts_culture: 2, family_oriented: 2, expat_friendly: 1 },
    'Mile-High City: sunny, dry, and a gateway to the Rocky Mountains. Growing fast as a remote-work destination.',
  ),
  c(
    'miami-us',
    'Miami',
    'United States',
    'US',
    'North America',
    25.7617,
    -80.1918,
    'Tropical',
    2,
    1,
    3,
    4,
    { tech: 1, finance: 2, healthcare: 1, creative: 2, manufacturing: 0 },
    { urban: 2, suburban: 1, rural: 0, coastal: 3, mountain: 0, arts_culture: 2, family_oriented: 1, expat_friendly: 3 },
    'Tropical coastal hub with strong Latin American ties, an active nightlife, and growing tech investment.',
  ),
  c(
    'portland-us',
    'Portland',
    'United States',
    'US',
    'North America',
    45.5152,
    -122.6784,
    'Temperate',
    2,
    2,
    4,
    4,
    { tech: 2, finance: 1, healthcare: 1, creative: 2, manufacturing: 1 },
    { urban: 2, suburban: 1, rural: 0, coastal: 1, mountain: 2, arts_culture: 3, family_oriented: 1, expat_friendly: 1 },
    'Pacific Northwest city famous for its food carts, indie culture, and easy access to mountains and ocean.',
  ),
  c(
    'montreal-ca',
    'Montréal',
    'Canada',
    'CA',
    'North America',
    45.5017,
    -73.5673,
    'Continental',
    3,
    2,
    5,
    4,
    { tech: 2, finance: 1, healthcare: 1, creative: 3, manufacturing: 1 },
    { urban: 2, suburban: 1, rural: 0, coastal: 0, mountain: 0, arts_culture: 3, family_oriented: 1, expat_friendly: 2 },
    "Francophone North American city with the lowest rent among Canadian majors, a thriving AI and games industry, and a celebrated food scene.",
  ),
  c(
    'mexico-city-mx',
    'Mexico City',
    'Mexico',
    'MX',
    'North America',
    19.4326,
    -99.1332,
    'Highland',
    4,
    4,
    4,
    3,
    { tech: 2, finance: 1, healthcare: 1, creative: 2, manufacturing: 1 },
    { urban: 3, suburban: 1, rural: 0, coastal: 0, mountain: 1, arts_culture: 3, family_oriented: 1, expat_friendly: 2 },
    'Sprawling, high-altitude capital with deep history, a thriving arts scene, and one of the best food cultures in the Americas.',
  ),
  c(
    'los-angeles-us',
    'Los Angeles',
    'United States',
    'US',
    'North America',
    34.0522,
    -118.2437,
    'Mediterranean',
    1,
    1,
    4,
    4,
    { tech: 2, finance: 2, healthcare: 2, creative: 3, manufacturing: 2 },
    { urban: 2, suburban: 2, rural: 0, coastal: 3, mountain: 2, arts_culture: 3, family_oriented: 1, expat_friendly: 3 },
    'Car-dependent Pacific coast megacity centered on entertainment, tech, and the largest Mexican-American community in the U.S.',
  ),
  c(
    'atlanta-us',
    'Atlanta',
    'United States',
    'US',
    'North America',
    33.749,
    -84.388,
    'Temperate',
    3,
    2,
    4,
    4,
    { tech: 2, finance: 2, healthcare: 2, creative: 2, manufacturing: 1 },
    { urban: 2, suburban: 2, rural: 0, coastal: 0, mountain: 0, arts_culture: 2, family_oriented: 2, expat_friendly: 1 },
    "Southern business hub and home of the world's busiest airport. Fast-growing, with strong Black-American cultural institutions and a lower cost of living than coastal peers.",
  ),

  // -----------------------------------------------------------------------
  // Europe (10)
  // -----------------------------------------------------------------------
  c(
    'lisbon-pt',
    'Lisbon',
    'Portugal',
    'PT',
    'Europe',
    38.7223,
    -9.1393,
    'Mediterranean',
    4,
    4,
    4,
    4,
    { tech: 2, finance: 1, healthcare: 1, creative: 2, manufacturing: 1 },
    { urban: 2, suburban: 1, rural: 0, coastal: 3, mountain: 0, arts_culture: 2, family_oriented: 1, expat_friendly: 3 },
    'Atlantic-coast capital that has become Europe\'s leading digital-nomad hub, with the D7 visa and a famously low cost of living for Western Europe.',
  ),
  c(
    'porto-pt',
    'Porto',
    'Portugal',
    'PT',
    'Europe',
    41.1579,
    -8.6291,
    'Mediterranean',
    5,
    4,
    4,
    4,
    { tech: 1, finance: 0, healthcare: 1, creative: 1, manufacturing: 1 },
    { urban: 2, suburban: 1, rural: 0, coastal: 2, mountain: 0, arts_culture: 2, family_oriented: 1, expat_friendly: 2 },
    'Smaller, more traditional counterpart to Lisbon, with a strong identity, port-wine heritage, and lower cost of living.',
  ),
  c(
    'barcelona-es',
    'Barcelona',
    'Spain',
    'ES',
    'Europe',
    41.3851,
    2.1734,
    'Mediterranean',
    3,
    2,
    4,
    4,
    { tech: 2, finance: 1, healthcare: 2, creative: 2, manufacturing: 1 },
    { urban: 3, suburban: 0, rural: 0, coastal: 3, mountain: 0, arts_culture: 3, family_oriented: 1, expat_friendly: 3 },
    'Catalan capital with Mediterranean beaches, Gaudí architecture, and a strong startup scene. Famous for food and outdoor lifestyle.',
  ),
  c(
    'madrid-es',
    'Madrid',
    'Spain',
    'ES',
    'Europe',
    40.4168,
    -3.7038,
    'Mediterranean',
    3,
    2,
    4,
    5,
    { tech: 2, finance: 2, healthcare: 2, creative: 2, manufacturing: 1 },
    { urban: 3, suburban: 1, rural: 0, coastal: 0, mountain: 1, arts_culture: 3, family_oriented: 1, expat_friendly: 2 },
    'Spain\'s high-altitude capital, with vibrant nightlife, strong public healthcare, and lower living costs than Paris or London.',
  ),
  c(
    'berlin-de',
    'Berlin',
    'Germany',
    'DE',
    'Europe',
    52.52,
    13.405,
    'Continental',
    3,
    2,
    4,
    5,
    { tech: 3, finance: 1, healthcare: 2, creative: 3, manufacturing: 1 },
    { urban: 3, suburban: 1, rural: 0, coastal: 0, mountain: 0, arts_culture: 3, family_oriented: 0, expat_friendly: 3 },
    'Germany\'s startup capital: cheap by Western European standards, intensely creative, and a magnet for English-speaking expats.',
  ),
  c(
    'amsterdam-nl',
    'Amsterdam',
    'Netherlands',
    'NL',
    'Europe',
    52.3676,
    4.9041,
    'Temperate',
    2,
    1,
    5,
    5,
    { tech: 3, finance: 2, healthcare: 2, creative: 2, manufacturing: 1 },
    { urban: 2, suburban: 2, rural: 0, coastal: 1, mountain: 0, arts_culture: 3, family_oriented: 2, expat_friendly: 3 },
    'Compact canal city with the highest English proficiency in continental Europe and one of the strongest startup / tech ecosystems.',
  ),
  c(
    'paris-fr',
    'Paris',
    'France',
    'FR',
    'Europe',
    48.8566,
    2.3522,
    'Temperate',
    2,
    1,
    5,
    5,
    { tech: 2, finance: 3, healthcare: 2, creative: 3, manufacturing: 2 },
    { urban: 3, suburban: 1, rural: 0, coastal: 0, mountain: 0, arts_culture: 3, family_oriented: 1, expat_friendly: 2 },
    'Global capital for culture, fashion, and finance. Expensive to live in, but with a strong public services backbone.',
  ),
  c(
    'london-uk',
    'London',
    'United Kingdom',
    'GB',
    'Europe',
    51.5074,
    -0.1278,
    'Temperate',
    1,
    1,
    5,
    4,
    { tech: 3, finance: 3, healthcare: 2, creative: 3, manufacturing: 1 },
    { urban: 3, suburban: 1, rural: 0, coastal: 1, mountain: 0, arts_culture: 3, family_oriented: 1, expat_friendly: 3 },
    'Europe\'s largest financial centre and a global hub for tech, creative industries, and academia. Among the most expensive cities worldwide.',
  ),
  c(
    'zurich-ch',
    'Zürich',
    'Switzerland',
    'CH',
    'Europe',
    47.3769,
    8.5417,
    'Continental',
    1,
    1,
    5,
    5,
    { tech: 2, finance: 3, healthcare: 2, creative: 1, manufacturing: 2 },
    { urban: 2, suburban: 2, rural: 0, coastal: 0, mountain: 2, arts_culture: 2, family_oriented: 2, expat_friendly: 1 },
    'Wealthy, efficient, and orderly Alpine city. Among the highest salaries and the highest costs of living in the world.',
  ),
  c(
    'prague-cz',
    'Prague',
    'Czechia',
    'CZ',
    'Europe',
    50.0755,
    14.4378,
    'Continental',
    5,
    4,
    4,
    4,
    { tech: 2, finance: 1, healthcare: 1, creative: 1, manufacturing: 2 },
    { urban: 2, suburban: 1, rural: 0, coastal: 0, mountain: 0, arts_culture: 2, family_oriented: 1, expat_friendly: 2 },
    'Central European capital with a beautiful historic core, low cost of living, and a fast-growing tech scene.',
  ),

  // -----------------------------------------------------------------------
  // Asia-Pacific (5)
  // -----------------------------------------------------------------------
  c(
    'singapore-sg',
    'Singapore',
    'Singapore',
    'SG',
    'Asia-Pacific',
    1.3521,
    103.8198,
    'Tropical',
    1,
    1,
    5,
    5,
    { tech: 3, finance: 3, healthcare: 3, creative: 1, manufacturing: 2 },
    { urban: 3, suburban: 1, rural: 0, coastal: 1, mountain: 0, arts_culture: 2, family_oriented: 2, expat_friendly: 3 },
    'City-state that consistently tops global rankings for education, healthcare, and ease of doing business.',
  ),
  c(
    'tokyo-jp',
    'Tokyo',
    'Japan',
    'JP',
    'Asia-Pacific',
    35.6762,
    139.6503,
    'Temperate',
    2,
    1,
    5,
    5,
    { tech: 3, finance: 3, healthcare: 3, creative: 3, manufacturing: 3 },
    { urban: 3, suburban: 1, rural: 0, coastal: 1, mountain: 1, arts_culture: 3, family_oriented: 1, expat_friendly: 1 },
    'The world\'s largest metropolitan economy: ultra-safe, ultra-efficient, with famously low crime and excellent public transport.',
  ),
  c(
    'seoul-kr',
    'Seoul',
    'South Korea',
    'KR',
    'Asia-Pacific',
    37.5665,
    126.978,
    'Continental',
    3,
    2,
    5,
    5,
    { tech: 3, finance: 2, healthcare: 2, creative: 3, manufacturing: 2 },
    { urban: 3, suburban: 1, rural: 0, coastal: 0, mountain: 1, arts_culture: 2, family_oriented: 1, expat_friendly: 1 },
    'Northeast Asian megacity famous for K-culture, ubiquitous connectivity, and a fast-growing startup scene.',
  ),
  c(
    'sydney-au',
    'Sydney',
    'Australia',
    'AU',
    'Asia-Pacific',
    -33.8688,
    151.2093,
    'Temperate',
    1,
    1,
    5,
    5,
    { tech: 2, finance: 3, healthcare: 2, creative: 2, manufacturing: 1 },
    { urban: 2, suburban: 2, rural: 0, coastal: 3, mountain: 0, arts_culture: 2, family_oriented: 2, expat_friendly: 2 },
    'Harbour city with a Mediterranean climate, strong points-based immigration pathways, and high quality of life.',
  ),
  c(
    'bangkok-th',
    'Bangkok',
    'Thailand',
    'TH',
    'Asia-Pacific',
    13.7563,
    100.5018,
    'Tropical',
    5,
    4,
    4,
    3,
    { tech: 1, finance: 1, healthcare: 2, creative: 1, manufacturing: 1 },
    { urban: 3, suburban: 1, rural: 0, coastal: 0, mountain: 0, arts_culture: 2, family_oriented: 1, expat_friendly: 3 },
    'Southeast Asian megacity famous for food, low cost of living, and a large long-stay expat community.',
  ),

  // -----------------------------------------------------------------------
  // Latin America (5)
  // -----------------------------------------------------------------------
  c(
    'buenos-aires-ar',
    'Buenos Aires',
    'Argentina',
    'AR',
    'Latin America',
    -34.6037,
    -58.3816,
    'Temperate',
    5,
    5,
    4,
    3,
    { tech: 2, finance: 1, healthcare: 1, creative: 2, manufacturing: 0 },
    { urban: 3, suburban: 1, rural: 0, coastal: 0, mountain: 0, arts_culture: 3, family_oriented: 1, expat_friendly: 2 },
    'Paris of South America: tango, steak, and European architecture, with chronic currency instability that distorts expat budgets.',
  ),
  c(
    'santiago-cl',
    'Santiago',
    'Chile',
    'CL',
    'Latin America',
    -33.4489,
    -70.6693,
    'Mediterranean',
    4,
    3,
    4,
    4,
    { tech: 1, finance: 1, healthcare: 1, creative: 1, manufacturing: 1 },
    { urban: 2, suburban: 2, rural: 0, coastal: 0, mountain: 3, arts_culture: 1, family_oriented: 1, expat_friendly: 1 },
    'Modern, mid-sized Andean capital framed by the Andes. Most stable economy and strongest institutions in the region.',
  ),
  c(
    'lima-pe',
    'Lima',
    'Peru',
    'PE',
    'Latin America',
    -12.0464,
    -77.0428,
    'Arid',
    4,
    4,
    3,
    3,
    { tech: 1, finance: 0, healthcare: 1, creative: 1, manufacturing: 0 },
    { urban: 2, suburban: 1, rural: 0, coastal: 2, mountain: 0, arts_culture: 2, family_oriented: 1, expat_friendly: 1 },
    'Coastal Pacific capital with a world-class food scene, and an arid microclimate kept cool by the Humboldt current.',
  ),
  c(
    'sao-paulo-br',
    'São Paulo',
    'Brazil',
    'BR',
    'Latin America',
    -23.5505,
    -46.6333,
    'Tropical',
    3,
    2,
    4,
    2,
    { tech: 2, finance: 2, healthcare: 2, creative: 2, manufacturing: 2 },
    { urban: 3, suburban: 1, rural: 0, coastal: 0, mountain: 0, arts_culture: 2, family_oriented: 1, expat_friendly: 1 },
    "Latin America's largest economy, with a dense, multicultural population and a strong business / tech scene.",
  ),
  c(
    'medellin-co',
    'Medellín',
    'Colombia',
    'CO',
    'Latin America',
    6.2476,
    -75.5658,
    'Tropical',
    5,
    4,
    3,
    3,
    { tech: 1, finance: 0, healthcare: 1, creative: 1, manufacturing: 0 },
    { urban: 2, suburban: 1, rural: 0, coastal: 0, mountain: 2, arts_culture: 1, family_oriented: 1, expat_friendly: 2 },
    'Once notorious, now a model of urban transformation: year-round spring weather, growing digital nomad scene, and a strong sense of place.',
  ),

  // -----------------------------------------------------------------------
  // Other (5) — Cape Town, Dubai, Tel Aviv, Istanbul, Casablanca
  // -----------------------------------------------------------------------
  c(
    'cape-town-za',
    'Cape Town',
    'South Africa',
    'ZA',
    'Other',
    -33.9249,
    18.4241,
    'Mediterranean',
    4,
    3,
    4,
    3,
    { tech: 1, finance: 1, healthcare: 1, creative: 2, manufacturing: 0 },
    { urban: 2, suburban: 1, rural: 0, coastal: 3, mountain: 3, arts_culture: 2, family_oriented: 1, expat_friendly: 2 },
    'Coastal city below Table Mountain: Mediterranean climate, strong food / wine culture, and a critical-skills visa pathway.',
  ),
  c(
    'dubai-ae',
    'Dubai',
    'United Arab Emirates',
    'AE',
    'Other',
    25.2048,
    55.2708,
    'Arid',
    1,
    1,
    4,
    4,
    { tech: 2, finance: 3, healthcare: 1, creative: 1, manufacturing: 1 },
    { urban: 3, suburban: 1, rural: 0, coastal: 2, mountain: 0, arts_culture: 1, family_oriented: 1, expat_friendly: 3 },
    'Zero-income-tax Gulf city with a heavily expat population, a luxury lifestyle, and the Golden Visa long-stay program.',
  ),
  c(
    'tel-aviv-il',
    'Tel Aviv',
    'Israel',
    'IL',
    'Other',
    32.0853,
    34.7818,
    'Mediterranean',
    2,
    1,
    5,
    4,
    { tech: 3, finance: 2, healthcare: 2, creative: 3, manufacturing: 1 },
    { urban: 3, suburban: 0, rural: 0, coastal: 3, mountain: 0, arts_culture: 2, family_oriented: 1, expat_friendly: 2 },
    'Mediterranean tech hub, second only to Silicon Valley in startup density per capita. Beach-and-business lifestyle.',
  ),
  c(
    'istanbul-tr',
    'Istanbul',
    'Türkiye',
    'TR',
    'Other',
    41.0082,
    28.9784,
    'Temperate',
    4,
    3,
    3,
    3,
    { tech: 1, finance: 1, healthcare: 2, creative: 2, manufacturing: 1 },
    { urban: 3, suburban: 1, rural: 0, coastal: 2, mountain: 0, arts_culture: 2, family_oriented: 1, expat_friendly: 1 },
    'Transcontinental megacity straddling Europe and Asia, with deep history, a strong food culture, and a recently launched citizenship-by-investment path.',
  ),
  c(
    'casablanca-ma',
    'Casablanca',
    'Morocco',
    'MA',
    'Other',
    33.5731,
    -7.5898,
    'Mediterranean',
    4,
    4,
    3,
    3,
    { tech: 1, finance: 1, healthcare: 1, creative: 1, manufacturing: 1 },
    { urban: 2, suburban: 1, rural: 0, coastal: 2, mountain: 0, arts_culture: 1, family_oriented: 1, expat_friendly: 1 },
    "Morocco's Atlantic-coast business hub, with French as a working language and an affordable Mediterranean lifestyle.",
  ),
];
